"""Curated check_id -> generic title catalog.

Master copy. `sync_check_titles.py` mirrors this module into the findings
Lambdas; never hand-edit those copies. See
docs/superpowers/specs/2026-05-20-check-title-catalog-design.md.
"""
from __future__ import annotations

import re


def _fallback_title(raw_title: str) -> str:
    """Strip single-quoted resource names from a Shasta per-result title.

    Defense-in-depth for any check_id absent from CHECK_TITLES. Mirrors the
    former client-side genericizeTitle heuristic.
    """
    stripped = re.sub(r"\s*'[^']*'", "", raw_title)
    stripped = re.sub(r"\s{2,}", " ", stripped).strip()
    return stripped or raw_title


def resolve_check_title(check_id: str, raw_title: str) -> str:
    """Generic title for a finding: catalogued title, else stripped raw title."""
    return CHECK_TITLES.get(check_id) or _fallback_title(raw_title)


# Curated check_id -> generic title. Sorted by key. Covers every static
# check_id Shasta declares; sync_check_titles.py mirrors this into the
# findings Lambdas. The completeness test guards against drift from Shasta.
CHECK_TITLES: dict[str, str] = {
    # --- AWS: API Gateway, ACM ---
    "acm-expiring-certs": "ACM certificates are not nearing expiry",
    "apigw-authorizer": "API Gateway routes require an authorizer",
    "apigw-client-cert": "API Gateway uses client certificates for backend authentication",
    "apigw-logging": "API Gateway has execution and access logging enabled",
    "apigw-request-validation": "API Gateway has request validation enabled",
    "apigw-throttling": "API Gateway has throttling limits configured",
    "apigw-waf": "API Gateway is protected by a WAF web ACL",
    # --- AWS: Backup ---
    "aws-backup-cross-region-copy": "AWS Backup plans copy recovery points across regions",
    "aws-backup-plans": "AWS Backup plans are configured",
    "aws-backup-policy": "An AWS Organizations backup policy is enforced",
    "aws-backup-vault-access-policy": "AWS Backup vaults have a resource access policy",
    "aws-backup-vault-cmk": "AWS Backup vaults are encrypted with a customer-managed key",
    "aws-backup-vault-exists": "An AWS Backup vault exists",
    "aws-backup-vault-lock": "AWS Backup vaults have Vault Lock enabled",
    # --- AWS: Organizations, Config, governance ---
    "aws-config-conformance-packs": "AWS Config conformance packs are deployed",
    "aws-delegated-admin": "AWS Organizations delegated administration is configured",
    "aws-org-enabled": "AWS Organizations is enabled",
    "aws-org-scps": "AWS Organizations service control policies are applied",
    "aws-tag-policy": "AWS Organizations tag policies are enforced",
    "aws-vpc-endpoints": "VPC endpoints are used for AWS service access",
    # --- AWS: CloudFront ---
    "cloudfront-geo-restrictions": "CloudFront distributions enforce geo restrictions",
    "cloudfront-https-only": "CloudFront distributions require HTTPS",
    "cloudfront-min-tls": "CloudFront distributions enforce a modern minimum TLS version",
    "cloudfront-oac": "CloudFront distributions use origin access control",
    "cloudfront-waf": "CloudFront distributions are protected by a WAF web ACL",
    # --- AWS: CloudTrail ---
    "cloudtrail-ai-events": "CloudTrail records AI service data events",
    "cloudtrail-enabled": "CloudTrail is enabled across all regions",
    "cloudtrail-kms-encryption": "CloudTrail logs are encrypted with KMS",
    "cloudtrail-log-validation": "CloudTrail log file validation is enabled",
    "cloudtrail-s3-object-lock": "The CloudTrail log bucket has S3 Object Lock enabled",
    # --- AWS: CloudWatch, Config, log groups ---
    "cloudwatch-alarms-cis-4": "CloudWatch alarms cover CIS-recommended events",
    "config-enabled": "The AWS Config recorder is enabled",
    "cwl-kms-encryption": "CloudWatch log groups are encrypted with KMS",
    "cwl-retention": "CloudWatch log groups have a retention period set",
    # --- AWS: databases ---
    "docdb-audit-logs": "DocumentDB clusters have audit logging enabled",
    "docdb-encryption": "DocumentDB clusters are encrypted at rest",
    "dynamodb-kms": "DynamoDB tables are encrypted with a KMS key",
    "dynamodb-pitr": "DynamoDB tables have point-in-time recovery enabled",
    "neptune-encryption": "Neptune clusters are encrypted at rest",
    "rds-auto-minor-upgrade": "RDS instances have automatic minor version upgrades enabled",
    "rds-backup-enabled": "RDS instances have automated backups enabled",
    "rds-deletion-protection": "RDS instances have deletion protection enabled",
    "rds-encryption-at-rest": "RDS instances are encrypted at rest",
    "rds-force-ssl": "RDS instances enforce SSL connections",
    "rds-iam-auth": "RDS instances have IAM database authentication enabled",
    "rds-min-tls": "RDS instances enforce a modern minimum TLS version",
    "rds-no-public-access": "RDS instances are not publicly accessible",
    "rds-pi-kms": "RDS Performance Insights data is encrypted with a KMS key",
    "rds-postgres-log-settings": "RDS PostgreSQL instances have secure logging settings",
    "redshift-audit-logging": "Redshift clusters have audit logging enabled",
    "redshift-encryption": "Redshift clusters are encrypted at rest",
    "redshift-public-access": "Redshift clusters are not publicly accessible",
    "redshift-require-ssl": "Redshift clusters require SSL connections",
    "elasticache-at-rest-encryption": "ElastiCache clusters are encrypted at rest",
    "elasticache-auth-token": "ElastiCache clusters require an auth token",
    "elasticache-transit-encryption": "ElastiCache clusters encrypt data in transit",
    # --- AWS: storage volumes ---
    "ebs-encryption-by-default": "EBS encryption by default is enabled",
    "ebs-volume-encrypted": "EBS volumes are encrypted",
    "efs-encryption": "EFS file systems are encrypted at rest",
    # --- AWS: EC2, ECS, EKS ---
    "ec2-ami-age": "EC2 instances run reasonably recent AMIs",
    "ec2-imdsv2-enforced": "EC2 instances enforce IMDSv2",
    "ec2-instance-profile": "EC2 instances use an IAM instance profile",
    "ec2-public-ips": "EC2 instances avoid unnecessary public IP addresses",
    "ecs-task-privileged": "ECS task definitions do not run privileged containers",
    "ecs-task-root-user": "ECS task containers do not run as the root user",
    "eks-audit-logging": "EKS clusters have audit logging enabled",
    "eks-private-endpoint": "EKS cluster API endpoints are private",
    "eks-secrets-encryption": "EKS clusters encrypt secrets with KMS",
    # --- AWS: load balancing ---
    "elb-access-logs": "Load balancers have access logging enabled",
    "elb-drop-invalid-headers": "Load balancers drop invalid HTTP headers",
    "elb-listener-tls": "Load balancer listeners enforce TLS",
    # --- AWS: detection services ---
    "guardduty-enabled": "GuardDuty is enabled",
    "guardduty-no-active-findings": "GuardDuty has no unresolved active findings",
    "inspector-critical-findings": "Inspector has no unresolved critical findings",
    "inspector-enabled": "Amazon Inspector is enabled",
    "inspector-network-reachability": "Inspector network reachability assessment is enabled",
    "security-hub-enabled": "AWS Security Hub is enabled",
    # --- AWS: IAM ---
    "iam-access-analyzer": "IAM Access Analyzer is enabled",
    "iam-access-key-rotation": "IAM access keys are rotated regularly",
    "iam-inactive-user": "Inactive IAM users are removed",
    "iam-no-direct-policies": "IAM users have no directly attached policies",
    "iam-overprivileged-user": "IAM users do not hold administrative privileges",
    "iam-password-policy": "The IAM account password policy meets baseline requirements",
    "iam-policy-wildcards": "IAM policies avoid wildcard actions and resources",
    "iam-role-trust-external": "IAM role trust policies restrict external principals",
    "iam-root-access-keys": "The root account has no access keys",
    "iam-root-mfa": "The root account has MFA enabled",
    "iam-root-not-used": "The root account is not used for routine operations",
    "iam-unused-roles": "Unused IAM roles are removed",
    "iam-user-mfa": "IAM users have MFA enabled",
    # --- AWS: KMS ---
    "kms-key-policy-wildcards": "KMS key policies avoid wildcard principals",
    "kms-key-rotation": "KMS customer-managed keys have automatic rotation enabled",
    "kms-no-unrestricted-principal": "KMS key policies have no unrestricted principal",
    "kms-scheduled-deletion": "No KMS keys are pending scheduled deletion",
    # --- AWS: Lambda ---
    "lambda-ai-api-keys-not-hardcoded": "Lambda functions do not hardcode AI provider API keys",
    "lambda-code-signing": "Lambda functions enforce code signing",
    "lambda-dlq": "Lambda functions have a dead-letter queue configured",
    "lambda-env-kms": "Lambda environment variables are encrypted with a KMS key",
    "lambda-function-url-auth": "Lambda function URLs require authentication",
    "lambda-layer-origin": "Lambda layers come from trusted origins",
    "lambda-runtime-eol": "Lambda functions do not use end-of-life runtimes",
    # --- AWS: S3 ---
    "s3-access-logging": "S3 buckets have server access logging enabled",
    "s3-encryption-at-rest": "S3 buckets are encrypted at rest",
    "s3-kms-cmk": "S3 buckets are encrypted with a customer-managed KMS key",
    "s3-object-ownership": "S3 buckets enforce bucket-owner object ownership",
    "s3-public-access-block": "S3 buckets block public access",
    "s3-ssl-only": "S3 bucket policies require SSL-only access",
    "s3-training-data-encrypted": "S3 buckets holding AI training data are encrypted",
    "s3-training-data-versioned": "S3 buckets holding AI training data have versioning enabled",
    "s3-versioning": "S3 buckets have versioning enabled",
    # --- AWS: SageMaker, Bedrock ---
    "sagemaker-data-capture": "SageMaker endpoints have data capture configured",
    "sagemaker-endpoint-encryption": "SageMaker endpoints are encrypted with a KMS key",
    "sagemaker-model-approval": "SageMaker models require approval before deployment",
    "sagemaker-model-registry-access": "SageMaker model registry access is restricted",
    "sagemaker-notebook-root-access": "SageMaker notebook instances disable root access",
    "sagemaker-training-vpc": "SageMaker training jobs run inside a VPC",
    "bedrock-agent-guardrails": "Bedrock agents have guardrails attached",
    "bedrock-content-filter": "Bedrock guardrails enforce content filtering",
    "bedrock-guardrails-configured": "Bedrock guardrails are configured",
    "bedrock-model-invocation-logging": "Bedrock model invocation logging is enabled",
    "bedrock-vpc-endpoint": "Bedrock is accessed through a VPC endpoint",
    # --- AWS: networking, messaging, misc ---
    "sg-default-restricted": "Default security groups restrict all traffic",
    "sg-no-unrestricted-ingress": "Security groups have no unrestricted ingress",
    "vpc-flow-logs-enabled": "VPC flow logs are enabled",
    "sns-encryption": "SNS topics are encrypted at rest",
    "sqs-encryption": "SQS queues are encrypted at rest",
    "sfn-logging": "Step Functions state machines have logging enabled",
    "secrets-manager-rotation": "Secrets Manager secrets have rotation enabled",
    # --- Azure: monitoring + activity log ---
    "azure-activity-log": "Azure Activity Log is captured to a Log Analytics workspace",
    "azure-activity-log-alerts": "Azure Activity Log alerts are configured for critical operations",
    "azure-activity-log-retention": "Azure Activity Log retention meets the baseline period",
    "azure-diagnostic-settings": "Resources have diagnostic settings configured",
    "azure-monitor-alerts": "Azure Monitor alerts are configured for critical events",
    "azure-network-watcher-coverage": "Network Watcher is enabled in all regions",
    # --- Azure: identity + Entra ---
    "azure-admin-consent-workflow": "The Entra admin consent workflow is enabled",
    "azure-admin-portal-restricted": "Access to the Azure administration portals is restricted",
    "azure-app-registration-restricted": "Non-admin application registration is restricted",
    "azure-authentication-methods": "The Entra authentication methods policy meets the baseline",
    "azure-banned-password-protection": "Entra banned password protection is enabled",
    "azure-break-glass-accounts": "Emergency break-glass accounts are configured",
    "azure-classic-admins": "No Azure classic administrators remain",
    "azure-conditional-access-mfa": "Conditional Access requires multi-factor authentication",
    "azure-cross-tenant-access": "Entra cross-tenant access settings are restricted",
    "azure-custom-role-wildcards": "Azure custom roles avoid wildcard permissions",
    "azure-guest-access": "Entra guest user access is restricted",
    "azure-guest-access-restrictions": "Entra guest access permissions are restricted",
    "azure-guest-invitations": "Entra guest invitation permissions are restricted",
    "azure-inactive-users": "Inactive Entra user accounts are removed",
    "azure-legacy-auth-blocked": "Legacy authentication protocols are blocked",
    "azure-m365-group-creation": "Microsoft 365 group creation is restricted",
    "azure-mfa-azure-management": "Multi-factor authentication is required for Azure management",
    "azure-named-locations": "Conditional Access named locations are defined",
    "azure-pim-eligibility": "Privileged roles are assigned through PIM eligibility",
    "azure-privileged-roles": "Privileged directory role assignments are minimized",
    "azure-rbac-least-privilege": "Azure RBAC assignments follow least privilege",
    "azure-security-defaults": "Entra security defaults or equivalent policies are enabled",
    "azure-security-group-creation": "Security group creation is restricted",
    "azure-service-principal-hygiene": "Service principal credentials are well maintained",
    "azure-sign-in-risk-policy": "A sign-in risk Conditional Access policy is enabled",
    "azure-sspr-notifications": "Self-service password reset notifications are enabled",
    "azure-user-consent-apps": "User consent to applications is restricted",
    "azure-user-risk-policy": "A user risk Conditional Access policy is enabled",
    # --- Azure: governance ---
    "azure-defender-enabled": "Microsoft Defender for Cloud is enabled",
    "azure-defender-per-plan": "Microsoft Defender for Cloud plans are enabled per resource type",
    "azure-management-group-hierarchy": "A management group hierarchy is established",
    "azure-policy-compliance": "Azure Policy assignments are compliant",
    "azure-required-tags": "Resources carry the required governance tags",
    "azure-resource-locks": "Critical resources have resource locks applied",
    "azure-security-initiative": "The Microsoft cloud security benchmark initiative is assigned",
    # --- Azure: App Service ---
    "azure-appservice-auth": "App Service apps require authentication",
    "azure-appservice-client-cert": "App Service apps require client certificates",
    "azure-appservice-ftps": "App Service apps disable insecure FTP access",
    "azure-appservice-https-only": "App Service apps require HTTPS",
    "azure-appservice-managed-identity": "App Service apps use a managed identity",
    "azure-appservice-min-tls": "App Service apps enforce a modern minimum TLS version",
    "azure-appservice-public-access": "App Service apps restrict public network access",
    "azure-appservice-remote-debug": "App Service apps have remote debugging disabled",
    # --- Azure: databases ---
    "azure-cosmos-cmk": "Cosmos DB accounts are encrypted with a customer-managed key",
    "azure-cosmos-disable-local-auth": "Cosmos DB accounts disable local authentication",
    "azure-cosmos-firewall": "Cosmos DB accounts have firewall rules configured",
    "azure-cosmos-metadata-write": "Cosmos DB accounts restrict metadata write access",
    "azure-cosmos-public-access": "Cosmos DB accounts restrict public network access",
    "azure-mysql-audit-log": "Azure Database for MySQL has audit logging enabled",
    "azure-mysql-secure-transport": "Azure Database for MySQL requires secure transport",
    "azure-mysql-tls-version": "Azure Database for MySQL enforces a modern TLS version",
    "azure-postgres-log-settings": "Azure Database for PostgreSQL has secure logging settings",
    "azure-postgres-public-access": "Azure Database for PostgreSQL restricts public access",
    "azure-postgres-secure-transport": "Azure Database for PostgreSQL requires secure transport",
    "azure-sql-auditing": "Azure SQL servers have auditing enabled",
    "azure-sql-entra-admin": "Azure SQL servers have an Entra administrator configured",
    "azure-sql-min-tls": "Azure SQL servers enforce a modern minimum TLS version",
    "azure-sql-public-access": "Azure SQL servers restrict public network access",
    "azure-sql-tde": "Azure SQL databases have transparent data encryption enabled",
    # --- Azure: storage ---
    "azure-blob-public-access": "Storage accounts disallow public blob access",
    "azure-storage-cross-tenant-replication": "Storage accounts disable cross-tenant replication",
    "azure-storage-encryption": "Storage accounts are encrypted with a customer-managed key",
    "azure-storage-https-only": "Storage accounts require secure HTTPS transfer",
    "azure-storage-network-default-deny": "Storage accounts default to denying network access",
    "azure-storage-shared-key-access": "Storage accounts disable shared key access",
    "azure-storage-soft-delete": "Storage accounts have blob soft delete enabled",
    # --- Azure: Key Vault ---
    "azure-keyvault-config": "Key Vaults are configured to baseline standards",
    "azure-keyvault-key-expiry": "Key Vault keys have an expiry date set",
    "azure-keyvault-public-access": "Key Vaults restrict public network access",
    "azure-keyvault-rbac-mode": "Key Vaults use Azure RBAC for authorization",
    # --- Azure: networking ---
    "azure-nsg-default-restricted": "Default network security group rules are restrictive",
    "azure-nsg-unrestricted-ingress": "Network security groups have no unrestricted ingress",
    "azure-public-ip-exposure": "Resources avoid unnecessary public IP exposure",
    "azure-vnet-flow-logs": "Virtual networks have flow logs enabled",
    "azure-vnet-flow-logs-modern": "Virtual networks use modern VNet flow logs",
    "azure-disk-encryption": "Managed disks are encrypted",
    "azure-aks-rbac": "AKS clusters have Azure RBAC enabled",
    # --- Azure: private endpoints ---
    "azure-private-endpoint-account": "AI service accounts use a private endpoint",
    "azure-private-endpoint-databaseaccount": "Database accounts use a private endpoint",
    "azure-private-endpoint-registry": "Container registries use a private endpoint",
    "azure-private-endpoint-server": "Database servers use a private endpoint",
    "azure-private-endpoint-site": "App Service apps use a private endpoint",
    "azure-private-endpoint-storageaccount": "Storage accounts use a private endpoint",
    "azure-private-endpoint-vault": "Key Vaults use a private endpoint",
    # --- Azure: AI services ---
    "azure-ai-search-auth": "Azure AI Search uses Entra authentication",
    "azure-cognitive-cmk": "Azure AI services are encrypted with a customer-managed key",
    "azure-cognitive-network-rules": "Azure AI services restrict network access",
    "azure-openai-abuse-monitoring": "Azure OpenAI abuse monitoring is enabled",
    "azure-openai-content-filter": "Azure OpenAI deployments enforce content filtering",
    "azure-openai-diagnostic-logging": "Azure OpenAI resources have diagnostic logging enabled",
    "azure-openai-key-rotation": "Azure OpenAI account keys are rotated regularly",
    "azure-openai-managed-identity": "Azure OpenAI resources use a managed identity",
    "azure-openai-private-endpoint": "Azure OpenAI resources use a private endpoint",
    "azure-ml-compute-rbac": "Azure ML compute uses RBAC access control",
    "azure-ml-data-drift-monitor": "Azure ML deployments have data drift monitoring",
    "azure-ml-environment-pinned": "Azure ML environments are pinned to specific versions",
    "azure-ml-model-registration": "Azure ML models are tracked in the model registry",
    "azure-ml-workspace-encryption": "Azure ML workspaces are encrypted with a customer-managed key",
    "azure-responsible-ai-dashboard": "Azure ML models have a Responsible AI dashboard",
    # --- Azure: Recovery Services vaults ---
    "azure-rsv-cmk": "Recovery Services vaults use a customer-managed key",
    "azure-rsv-crr": "Recovery Services vaults have cross-region restore enabled",
    "azure-rsv-exists": "A Recovery Services vault exists",
    "azure-rsv-immutability": "Recovery Services vaults have immutability enabled",
    "azure-rsv-mua": "Recovery Services vaults have multi-user authorization enabled",
    "azure-rsv-public-access": "Recovery Services vaults restrict public network access",
    "azure-rsv-redundancy": "Recovery Services vaults use geo-redundant storage",
    "azure-rsv-soft-delete": "Recovery Services vaults have soft delete enabled",
    # --- GCP: logging + audit ---
    "gcp-audit-data-access": "Cloud Audit Logs capture data access events",
    "gcp-dns-logging": "Cloud DNS has query logging enabled",
    "gcp-log-metric-alerts": "Log-based metric alerts are configured",
    "gcp-log-metric-custom-role-changes": "A log metric alerts on custom role changes",
    "gcp-log-metric-firewall-changes": "A log metric alerts on firewall rule changes",
    "gcp-log-metric-project-ownership": "A log metric alerts on project ownership changes",
    "gcp-log-metric-vpc-changes": "A log metric alerts on VPC network changes",
    "gcp-log-retention": "Log buckets have an appropriate retention period",
    "gcp-log-sink": "A log sink exports logs for retention",
    # --- GCP: IAM ---
    "gcp-iam-no-allusers": "IAM policies do not grant access to allUsers or allAuthenticatedUsers",
    "gcp-iam-primitive-roles": "IAM policies avoid primitive roles",
    "gcp-iam-sa-key-rotation": "Service account keys are rotated regularly",
    "gcp-iam-sa-not-admin": "Service accounts are not granted admin roles",
    "gcp-iam-sa-token-creator": "The service account token creator role is tightly scoped",
    "gcp-iam-workload-identity": "Workload Identity Federation is used instead of service account keys",
    # --- GCP: compute + GKE ---
    "gcp-compute-default-sa-full-scope": "Compute instances avoid the default service account with full scopes",
    "gcp-compute-no-external-ip": "Compute instances do not have external IP addresses",
    "gcp-compute-os-login": "Compute instances have OS Login enabled",
    "gcp-compute-serial-port": "Compute instances have serial port access disabled",
    "gcp-compute-shielded-vm": "Compute instances run as Shielded VMs",
    "gcp-gke-network-policy": "GKE clusters have network policy enabled",
    "gcp-gke-node-auto-upgrade": "GKE node pools have auto-upgrade enabled",
    "gcp-gke-private-cluster": "GKE clusters are private",
    "gcp-gke-workload-identity": "GKE clusters use Workload Identity",
    # --- GCP: Cloud Run ---
    "gcp-cloudrun-binary-authorization": "Cloud Run services enforce Binary Authorization",
    "gcp-cloudrun-ingress-restricted": "Cloud Run services restrict ingress traffic",
    "gcp-cloudrun-no-default-sa": "Cloud Run services do not use the default service account",
    "gcp-cloudrun-no-plaintext-secrets": "Cloud Run services do not expose plaintext secrets",
    "gcp-cloudrun-no-unauth-access": "Cloud Run services do not allow unauthenticated access",
    # --- GCP: networking ---
    "gcp-firewall-admin-ports": "Firewall rules do not expose administrative ports",
    "gcp-network-default-not-created": "The default network is not in use",
    "gcp-subnet-flow-logs": "Subnets have VPC flow logs enabled",
    "gcp-subnet-private-google-access": "Subnets have Private Google Access enabled",
    # --- GCP: KMS ---
    "gcp-kms-key-rotation": "Cloud KMS keys have rotation configured",
    # --- GCP: storage + BigQuery ---
    "gcp-bigquery-cmek": "BigQuery datasets are encrypted with a customer-managed key",
    "gcp-bigquery-public-access": "BigQuery datasets are not publicly accessible",
    "gcp-storage-access-logging": "Cloud Storage buckets have access logging enabled",
    "gcp-storage-bucket-public-access": "Cloud Storage buckets are not publicly accessible",
    "gcp-storage-retention-policy": "Cloud Storage buckets have a retention policy",
    "gcp-storage-uniform-access": "Cloud Storage buckets enforce uniform bucket-level access",
    "gcp-storage-versioning": "Cloud Storage buckets have object versioning enabled",
    # --- GCP: Cloud SQL ---
    "gcp-sql-backups": "Cloud SQL instances have automated backups enabled",
    "gcp-sql-no-public-ip": "Cloud SQL instances do not have a public IP",
    "gcp-sql-require-ssl": "Cloud SQL instances require SSL connections",
    # --- GCP: scan diagnostics ---
    "gcp-project-scan-error": "A GCP project could not be fully assessed",
    # --- GitHub ---
    "github-branch-protection": "Repository default branches have protection enabled",
    "github-enforce-admins": "Branch protection rules are enforced for administrators",
    "github-no-force-push": "Repository branches disallow force pushes",
    "github-pr-reviews": "Repository branches require pull request reviews",
    "github-repo-access": "Repository collaborator access is appropriately scoped",
    "github-status-checks": "Repository branches require status checks to pass",
}
