"""FedRAMP (NIST SP 800-53 Rev 5) + PCI DSS v4.0.1 control mappings.

Master copy. sync_framework_map.py mirrors this module into the four
scanner Lambdas; never hand-edit those copies. See
docs/superpowers/specs/2026-05-20-fedramp-pci-framework-mappings-design.md.
"""
from __future__ import annotations


def merge_framework_map(
    check_id: str, frameworks: dict[str, list[str]],
) -> dict[str, list[str]]:
    """Return a copy of `frameworks` with `fedramp` / `pci_dss` controls
    added for `check_id` when the catalog maps it. Input is not mutated."""
    extra = FRAMEWORK_MAP.get(check_id)
    if not extra:
        return dict(frameworks)
    return {**frameworks, **extra}


# check_id -> {"fedramp": [NIST 800-53 Rev 5 IDs], "pci_dss": [v4.0.1 reqs]}.
# Partial coverage: a check appears only under a framework it satisfies.
# Purely structural checks (e.g. aws-org-enabled) are intentionally absent.
FRAMEWORK_MAP: dict[str, dict[str, list[str]]] = {
    # --- AWS: API Gateway, ACM ---
    "apigw-authorizer":         {"fedramp": ["AC-3"], "pci_dss": ["7.2.1"]},
    "apigw-client-cert":        {"fedramp": ["IA-3", "SC-8"]},
    "apigw-logging":            {"fedramp": ["AU-2", "AU-12"], "pci_dss": ["10.2.1"]},
    "apigw-request-validation": {"fedramp": ["SI-10"]},
    "apigw-throttling":         {"fedramp": ["SC-5"]},
    "apigw-waf":                {"fedramp": ["SC-7"], "pci_dss": ["6.4.2"]},
    "acm-expiring-certs":       {"fedramp": ["SC-12", "SC-17"], "pci_dss": ["4.2.1"]},
    # --- AWS: Backup ---
    "aws-backup-cross-region-copy":   {"fedramp": ["CP-9"]},
    "aws-backup-plans":               {"fedramp": ["CP-9"]},
    "aws-backup-policy":              {"fedramp": ["CP-9"]},
    "aws-backup-vault-access-policy": {"fedramp": ["CP-9", "AC-3"]},
    "aws-backup-vault-cmk":           {"fedramp": ["CP-9", "SC-28"]},
    "aws-backup-vault-exists":        {"fedramp": ["CP-9"]},
    "aws-backup-vault-lock":          {"fedramp": ["CP-9", "AU-9"]},
    # --- AWS: Organizations, Config, governance ---
    "aws-config-conformance-packs": {"fedramp": ["CM-6", "CA-7"]},
    "aws-org-scps":                 {"fedramp": ["AC-3", "CM-7"]},
    "aws-tag-policy":               {"fedramp": ["CM-8"]},
    "aws-vpc-endpoints":            {"fedramp": ["SC-7"]},
    # --- AWS: CloudFront ---
    "cloudfront-geo-restrictions": {"fedramp": ["AC-3", "SC-7"]},
    "cloudfront-https-only":       {"fedramp": ["SC-8", "SC-13"], "pci_dss": ["4.2.1"]},
    "cloudfront-min-tls":          {"fedramp": ["SC-8", "SC-13"], "pci_dss": ["4.2.1"]},
    "cloudfront-oac":              {"fedramp": ["AC-3"]},
    "cloudfront-waf":              {"fedramp": ["SC-7"], "pci_dss": ["6.4.2"]},
    # --- AWS: CloudTrail ---
    "cloudtrail-ai-events":      {"fedramp": ["AU-2", "AU-12"], "pci_dss": ["10.2.1"]},
    "cloudtrail-enabled":        {"fedramp": ["AU-2", "AU-12"], "pci_dss": ["10.2.1"]},
    "cloudtrail-kms-encryption": {"fedramp": ["AU-9", "SC-28"], "pci_dss": ["10.3.2"]},
    "cloudtrail-log-validation": {"fedramp": ["AU-9"], "pci_dss": ["10.3.4"]},
    "cloudtrail-s3-object-lock": {"fedramp": ["AU-9"], "pci_dss": ["10.3.2"]},
    # --- AWS: CloudWatch, Config, log groups ---
    "cloudwatch-alarms-cis-4": {"fedramp": ["AU-6", "SI-4"], "pci_dss": ["10.4.1"]},
    "config-enabled":          {"fedramp": ["CM-2", "CM-3", "CA-7"]},
    "cwl-kms-encryption":      {"fedramp": ["AU-9", "SC-28"], "pci_dss": ["10.3.2"]},
    "cwl-retention":           {"fedramp": ["AU-11"], "pci_dss": ["10.5.1"]},
    # --- AWS: databases ---
    "docdb-audit-logs":          {"fedramp": ["AU-2", "AU-12"], "pci_dss": ["10.2.1"]},
    "docdb-encryption":          {"fedramp": ["SC-28"], "pci_dss": ["3.5.1"]},
    "dynamodb-kms":              {"fedramp": ["SC-28"], "pci_dss": ["3.5.1"]},
    "dynamodb-pitr":             {"fedramp": ["CP-9"]},
    "neptune-encryption":        {"fedramp": ["SC-28"], "pci_dss": ["3.5.1"]},
    "rds-auto-minor-upgrade":    {"fedramp": ["SI-2"], "pci_dss": ["6.3.3"]},
    "rds-backup-enabled":        {"fedramp": ["CP-9"]},
    "rds-deletion-protection":   {"fedramp": ["CP-9"]},
    "rds-encryption-at-rest":    {"fedramp": ["SC-28"], "pci_dss": ["3.5.1"]},
    "rds-force-ssl":             {"fedramp": ["SC-8", "SC-13"], "pci_dss": ["4.2.1"]},
    "rds-iam-auth":              {"fedramp": ["IA-2", "AC-3"], "pci_dss": ["8.2.1"]},
    "rds-min-tls":               {"fedramp": ["SC-8", "SC-13"], "pci_dss": ["4.2.1"]},
    "rds-no-public-access":      {"fedramp": ["SC-7"], "pci_dss": ["1.4.1"]},
    "rds-pi-kms":                {"fedramp": ["SC-28"], "pci_dss": ["3.5.1"]},
    "rds-postgres-log-settings": {"fedramp": ["AU-2", "AU-12"], "pci_dss": ["10.2.1"]},
    "redshift-audit-logging":    {"fedramp": ["AU-2", "AU-12"], "pci_dss": ["10.2.1"]},
    "redshift-encryption":       {"fedramp": ["SC-28"], "pci_dss": ["3.5.1"]},
    "redshift-public-access":    {"fedramp": ["SC-7"], "pci_dss": ["1.4.1"]},
    "redshift-require-ssl":      {"fedramp": ["SC-8", "SC-13"], "pci_dss": ["4.2.1"]},
    "elasticache-at-rest-encryption": {"fedramp": ["SC-28"], "pci_dss": ["3.5.1"]},
    "elasticache-auth-token":         {"fedramp": ["IA-2", "AC-3"]},
    "elasticache-transit-encryption": {"fedramp": ["SC-8", "SC-13"], "pci_dss": ["4.2.1"]},
    # --- AWS: storage volumes ---
    "ebs-encryption-by-default": {"fedramp": ["SC-28"], "pci_dss": ["3.5.1"]},
    "ebs-volume-encrypted":      {"fedramp": ["SC-28"], "pci_dss": ["3.5.1"]},
    "efs-encryption":            {"fedramp": ["SC-28"], "pci_dss": ["3.5.1"]},
    # --- AWS: EC2, ECS, EKS ---
    "ec2-ami-age":          {"fedramp": ["SI-2"], "pci_dss": ["6.3.3"]},
    "ec2-imdsv2-enforced":  {"fedramp": ["CM-7", "AC-6"]},
    "ec2-instance-profile": {"fedramp": ["AC-6", "IA-2"]},
    "ec2-public-ips":       {"fedramp": ["SC-7"], "pci_dss": ["1.4.1"]},
    "ecs-task-privileged":  {"fedramp": ["AC-6", "CM-7"]},
    "ecs-task-root-user":   {"fedramp": ["AC-6", "CM-7"]},
    "eks-audit-logging":    {"fedramp": ["AU-2", "AU-12"], "pci_dss": ["10.2.1"]},
    "eks-private-endpoint": {"fedramp": ["SC-7"], "pci_dss": ["1.4.1"]},
    "eks-secrets-encryption": {"fedramp": ["SC-28"], "pci_dss": ["3.5.1"]},
    # --- AWS: load balancing ---
    "elb-access-logs":          {"fedramp": ["AU-2", "AU-12"], "pci_dss": ["10.2.1"]},
    "elb-drop-invalid-headers": {"fedramp": ["SC-7", "SI-10"]},
    "elb-listener-tls":         {"fedramp": ["SC-8", "SC-13"], "pci_dss": ["4.2.1"]},
    # --- AWS: detection services ---
    "guardduty-enabled":             {"fedramp": ["SI-4"], "pci_dss": ["11.5.1"]},
    "guardduty-no-active-findings":  {"fedramp": ["SI-4", "IR-4"], "pci_dss": ["11.5.1"]},
    "inspector-critical-findings":   {"fedramp": ["RA-5", "SI-2"], "pci_dss": ["6.3.1", "11.3.1"]},
    "inspector-enabled":             {"fedramp": ["RA-5"], "pci_dss": ["11.3.1"]},
    "inspector-network-reachability": {"fedramp": ["RA-5", "SC-7"], "pci_dss": ["11.3.1"]},
    "security-hub-enabled":          {"fedramp": ["CA-7", "SI-4"]},
    # --- AWS: IAM ---
    "iam-access-analyzer":     {"fedramp": ["AC-6", "CA-7"], "pci_dss": ["7.2.1"]},
    "iam-access-key-rotation": {"fedramp": ["IA-5"], "pci_dss": ["8.3.9"]},
    "iam-inactive-user":       {"fedramp": ["AC-2"], "pci_dss": ["8.2.6"]},
    "iam-no-direct-policies":  {"fedramp": ["AC-6"], "pci_dss": ["7.2.1"]},
    "iam-overprivileged-user": {"fedramp": ["AC-6"], "pci_dss": ["7.2.1"]},
    "iam-password-policy":     {"fedramp": ["IA-5"], "pci_dss": ["8.3.6"]},
    "iam-policy-wildcards":    {"fedramp": ["AC-6"], "pci_dss": ["7.2.1"]},
    "iam-role-trust-external": {"fedramp": ["AC-3", "AC-6"], "pci_dss": ["7.2.1"]},
    "iam-root-access-keys":    {"fedramp": ["AC-6", "IA-2"], "pci_dss": ["8.6.1"]},
    "iam-root-mfa":            {"fedramp": ["IA-2"], "pci_dss": ["8.4.1"]},
    "iam-root-not-used":       {"fedramp": ["AC-6"], "pci_dss": ["7.2.5"]},
    "iam-unused-roles":        {"fedramp": ["AC-2"], "pci_dss": ["7.2.1"]},
    "iam-user-mfa":            {"fedramp": ["IA-2"], "pci_dss": ["8.4.1"]},
    # --- AWS: KMS ---
    "kms-key-policy-wildcards":      {"fedramp": ["AC-6", "SC-12"]},
    "kms-key-rotation":              {"fedramp": ["SC-12"], "pci_dss": ["3.7.4"]},
    "kms-no-unrestricted-principal": {"fedramp": ["AC-6", "SC-12"]},
    "kms-scheduled-deletion":        {"fedramp": ["SC-12"]},
    # --- AWS: Lambda ---
    "lambda-ai-api-keys-not-hardcoded": {"fedramp": ["IA-5", "SC-28"], "pci_dss": ["8.6.2"]},
    "lambda-code-signing":      {"fedramp": ["SI-7", "CM-5"]},
    "lambda-dlq":               {"fedramp": ["SI-11"]},
    "lambda-env-kms":           {"fedramp": ["SC-28"], "pci_dss": ["3.5.1"]},
    "lambda-function-url-auth": {"fedramp": ["AC-3", "IA-2"], "pci_dss": ["7.2.1"]},
    "lambda-layer-origin":      {"fedramp": ["SI-7", "SR-3"]},
    "lambda-runtime-eol":       {"fedramp": ["SI-2"], "pci_dss": ["6.3.3"]},
    # --- AWS: S3 ---
    "s3-access-logging":         {"fedramp": ["AU-2", "AU-12"], "pci_dss": ["10.2.1"]},
    "s3-encryption-at-rest":     {"fedramp": ["SC-28"], "pci_dss": ["3.5.1"]},
    "s3-kms-cmk":                {"fedramp": ["SC-28", "SC-12"], "pci_dss": ["3.5.1"]},
    "s3-object-ownership":       {"fedramp": ["AC-3"]},
    "s3-public-access-block":    {"fedramp": ["SC-7", "AC-3"], "pci_dss": ["1.4.1"]},
    "s3-ssl-only":               {"fedramp": ["SC-8", "SC-13"], "pci_dss": ["4.2.1"]},
    "s3-training-data-encrypted": {"fedramp": ["SC-28"], "pci_dss": ["3.5.1"]},
    "s3-training-data-versioned": {"fedramp": ["CP-9", "SI-7"]},
    "s3-versioning":             {"fedramp": ["CP-9"]},
    # --- AWS: SageMaker, Bedrock ---
    "sagemaker-data-capture":          {"fedramp": ["AU-2", "AU-12"]},
    "sagemaker-endpoint-encryption":   {"fedramp": ["SC-28"], "pci_dss": ["3.5.1"]},
    "sagemaker-model-approval":        {"fedramp": ["CM-3", "SI-7"]},
    "sagemaker-model-registry-access": {"fedramp": ["AC-3", "AC-6"]},
    "sagemaker-notebook-root-access":  {"fedramp": ["AC-6", "CM-7"]},
    "sagemaker-training-vpc":          {"fedramp": ["SC-7"]},
    "bedrock-agent-guardrails":        {"fedramp": ["SI-4", "AC-4"]},
    "bedrock-content-filter":          {"fedramp": ["SI-4"]},
    "bedrock-guardrails-configured":   {"fedramp": ["SI-4"]},
    "bedrock-model-invocation-logging": {"fedramp": ["AU-2", "AU-12"]},
    "bedrock-vpc-endpoint":            {"fedramp": ["SC-7"]},
    # --- AWS: networking, messaging, misc ---
    "sg-default-restricted":     {"fedramp": ["SC-7", "AC-4"], "pci_dss": ["1.2.1"]},
    "sg-no-unrestricted-ingress": {"fedramp": ["SC-7", "AC-4"], "pci_dss": ["1.3.1"]},
    "vpc-flow-logs-enabled":     {"fedramp": ["AU-2", "SI-4"], "pci_dss": ["10.2.1"]},
    "sns-encryption":            {"fedramp": ["SC-28"], "pci_dss": ["3.5.1"]},
    "sqs-encryption":            {"fedramp": ["SC-28"], "pci_dss": ["3.5.1"]},
    "sfn-logging":               {"fedramp": ["AU-2", "AU-12"], "pci_dss": ["10.2.1"]},
    "secrets-manager-rotation":  {"fedramp": ["IA-5"], "pci_dss": ["8.3.9"]},
    # --- Azure: monitoring + activity log ---
    "azure-activity-log":           {"fedramp": ["AU-2", "AU-12"], "pci_dss": ["10.2.1"]},
    "azure-activity-log-alerts":    {"fedramp": ["AU-6", "SI-4"], "pci_dss": ["10.4.1"]},
    "azure-activity-log-retention": {"fedramp": ["AU-11"], "pci_dss": ["10.5.1"]},
    "azure-diagnostic-settings":    {"fedramp": ["AU-2", "AU-12"], "pci_dss": ["10.2.1"]},
    "azure-monitor-alerts":         {"fedramp": ["AU-6", "SI-4"], "pci_dss": ["10.4.1"]},
    "azure-network-watcher-coverage": {"fedramp": ["AU-2", "SI-4"]},
    # --- Azure: identity + Entra ---
    "azure-admin-consent-workflow":     {"fedramp": ["AC-6"]},
    "azure-admin-portal-restricted":    {"fedramp": ["AC-3", "AC-6"]},
    "azure-app-registration-restricted": {"fedramp": ["AC-6", "CM-7"]},
    "azure-authentication-methods":     {"fedramp": ["IA-2", "IA-5"]},
    "azure-banned-password-protection": {"fedramp": ["IA-5"], "pci_dss": ["8.3.6"]},
    "azure-break-glass-accounts":       {"fedramp": ["AC-2"]},
    "azure-classic-admins":             {"fedramp": ["AC-6", "AC-2"]},
    "azure-conditional-access-mfa":     {"fedramp": ["IA-2"], "pci_dss": ["8.4.1"]},
    "azure-cross-tenant-access":        {"fedramp": ["AC-3", "AC-4"]},
    "azure-custom-role-wildcards":      {"fedramp": ["AC-6"], "pci_dss": ["7.2.1"]},
    "azure-guest-access":               {"fedramp": ["AC-2", "AC-3"]},
    "azure-guest-access-restrictions":  {"fedramp": ["AC-3", "AC-6"]},
    "azure-guest-invitations":          {"fedramp": ["AC-2"]},
    "azure-inactive-users":             {"fedramp": ["AC-2"], "pci_dss": ["8.2.6"]},
    "azure-legacy-auth-blocked":        {"fedramp": ["IA-2", "CM-7"]},
    "azure-m365-group-creation":        {"fedramp": ["AC-6", "CM-7"]},
    "azure-mfa-azure-management":       {"fedramp": ["IA-2"], "pci_dss": ["8.4.1"]},
    "azure-named-locations":            {"fedramp": ["AC-17"]},
    "azure-pim-eligibility":            {"fedramp": ["AC-2", "AC-6"], "pci_dss": ["7.2.1"]},
    "azure-privileged-roles":           {"fedramp": ["AC-6", "AC-2"], "pci_dss": ["7.2.1"]},
    "azure-rbac-least-privilege":       {"fedramp": ["AC-6"], "pci_dss": ["7.2.1"]},
    "azure-security-defaults":          {"fedramp": ["IA-2", "AC-6"]},
    "azure-security-group-creation":    {"fedramp": ["AC-6", "CM-7"]},
    "azure-service-principal-hygiene":  {"fedramp": ["IA-5"], "pci_dss": ["8.6.1"]},
    "azure-sign-in-risk-policy":        {"fedramp": ["AC-2", "SI-4"]},
    "azure-sspr-notifications":         {"fedramp": ["IA-5", "SI-4"]},
    "azure-user-consent-apps":          {"fedramp": ["AC-6", "CM-7"]},
    "azure-user-risk-policy":           {"fedramp": ["AC-2", "SI-4"]},
    # --- Azure: governance ---
    "azure-defender-enabled":   {"fedramp": ["SI-4", "RA-5"], "pci_dss": ["11.5.1"]},
    "azure-defender-per-plan":  {"fedramp": ["SI-4", "RA-5"], "pci_dss": ["11.5.1"]},
    "azure-policy-compliance":  {"fedramp": ["CM-6", "CA-7"]},
    "azure-required-tags":      {"fedramp": ["CM-8"]},
    "azure-resource-locks":     {"fedramp": ["CM-5"]},
    "azure-security-initiative": {"fedramp": ["CA-7", "CM-6"]},
    # --- Azure: App Service ---
    "azure-appservice-auth":             {"fedramp": ["AC-3", "IA-2"], "pci_dss": ["7.2.1"]},
    "azure-appservice-client-cert":      {"fedramp": ["IA-3", "SC-8"]},
    "azure-appservice-ftps":             {"fedramp": ["SC-8", "CM-7"], "pci_dss": ["4.2.1"]},
    "azure-appservice-https-only":       {"fedramp": ["SC-8", "SC-13"], "pci_dss": ["4.2.1"]},
    "azure-appservice-managed-identity": {"fedramp": ["IA-2", "IA-5"], "pci_dss": ["8.6.1"]},
    "azure-appservice-min-tls":          {"fedramp": ["SC-8", "SC-13"], "pci_dss": ["4.2.1"]},
    "azure-appservice-public-access":    {"fedramp": ["SC-7"], "pci_dss": ["1.4.1"]},
    "azure-appservice-remote-debug":     {"fedramp": ["CM-7"]},
    # --- Azure: databases ---
    "azure-cosmos-cmk":               {"fedramp": ["SC-28", "SC-12"], "pci_dss": ["3.5.1"]},
    "azure-cosmos-disable-local-auth": {"fedramp": ["IA-2", "AC-3"]},
    "azure-cosmos-firewall":          {"fedramp": ["SC-7"], "pci_dss": ["1.3.1"]},
    "azure-cosmos-metadata-write":    {"fedramp": ["AC-6"]},
    "azure-cosmos-public-access":     {"fedramp": ["SC-7"], "pci_dss": ["1.4.1"]},
    "azure-mysql-audit-log":          {"fedramp": ["AU-2", "AU-12"], "pci_dss": ["10.2.1"]},
    "azure-mysql-secure-transport":   {"fedramp": ["SC-8", "SC-13"], "pci_dss": ["4.2.1"]},
    "azure-mysql-tls-version":        {"fedramp": ["SC-8", "SC-13"], "pci_dss": ["4.2.1"]},
    "azure-postgres-log-settings":    {"fedramp": ["AU-2", "AU-12"], "pci_dss": ["10.2.1"]},
    "azure-postgres-public-access":   {"fedramp": ["SC-7"], "pci_dss": ["1.4.1"]},
    "azure-postgres-secure-transport": {"fedramp": ["SC-8", "SC-13"], "pci_dss": ["4.2.1"]},
    "azure-sql-auditing":             {"fedramp": ["AU-2", "AU-12"], "pci_dss": ["10.2.1"]},
    "azure-sql-entra-admin":          {"fedramp": ["IA-2", "AC-3"]},
    "azure-sql-min-tls":              {"fedramp": ["SC-8", "SC-13"], "pci_dss": ["4.2.1"]},
    "azure-sql-public-access":        {"fedramp": ["SC-7"], "pci_dss": ["1.4.1"]},
    "azure-sql-tde":                  {"fedramp": ["SC-28"], "pci_dss": ["3.5.1"]},
    # --- Azure: storage ---
    "azure-blob-public-access":              {"fedramp": ["SC-7", "AC-3"], "pci_dss": ["1.4.1"]},
    "azure-storage-cross-tenant-replication": {"fedramp": ["AC-3", "SC-7"]},
    "azure-storage-encryption":              {"fedramp": ["SC-28", "SC-12"], "pci_dss": ["3.5.1"]},
    "azure-storage-https-only":              {"fedramp": ["SC-8", "SC-13"], "pci_dss": ["4.2.1"]},
    "azure-storage-network-default-deny":    {"fedramp": ["SC-7"], "pci_dss": ["1.4.1"]},
    "azure-storage-shared-key-access":       {"fedramp": ["IA-2", "AC-3"]},
    "azure-storage-soft-delete":             {"fedramp": ["CP-9"]},
    # --- Azure: Key Vault ---
    "azure-keyvault-config":        {"fedramp": ["SC-12"]},
    "azure-keyvault-key-expiry":    {"fedramp": ["SC-12"], "pci_dss": ["3.7.4"]},
    "azure-keyvault-public-access": {"fedramp": ["SC-7"], "pci_dss": ["1.4.1"]},
    "azure-keyvault-rbac-mode":     {"fedramp": ["AC-3", "AC-6"]},
    # --- Azure: networking ---
    "azure-nsg-default-restricted":   {"fedramp": ["SC-7", "AC-4"], "pci_dss": ["1.2.1"]},
    "azure-nsg-unrestricted-ingress": {"fedramp": ["SC-7", "AC-4"], "pci_dss": ["1.3.1"]},
    "azure-public-ip-exposure":       {"fedramp": ["SC-7"], "pci_dss": ["1.4.1"]},
    "azure-vnet-flow-logs":           {"fedramp": ["AU-2", "SI-4"], "pci_dss": ["10.2.1"]},
    "azure-vnet-flow-logs-modern":    {"fedramp": ["AU-2", "SI-4"], "pci_dss": ["10.2.1"]},
    "azure-disk-encryption":          {"fedramp": ["SC-28"], "pci_dss": ["3.5.1"]},
    "azure-aks-rbac":                 {"fedramp": ["AC-3", "AC-6"], "pci_dss": ["7.2.1"]},
    # --- Azure: private endpoints ---
    "azure-private-endpoint-account":         {"fedramp": ["SC-7"], "pci_dss": ["1.4.1"]},
    "azure-private-endpoint-databaseaccount": {"fedramp": ["SC-7"], "pci_dss": ["1.4.1"]},
    "azure-private-endpoint-registry":        {"fedramp": ["SC-7"], "pci_dss": ["1.4.1"]},
    "azure-private-endpoint-server":          {"fedramp": ["SC-7"], "pci_dss": ["1.4.1"]},
    "azure-private-endpoint-site":            {"fedramp": ["SC-7"], "pci_dss": ["1.4.1"]},
    "azure-private-endpoint-storageaccount":  {"fedramp": ["SC-7"], "pci_dss": ["1.4.1"]},
    "azure-private-endpoint-vault":           {"fedramp": ["SC-7"], "pci_dss": ["1.4.1"]},
    # --- Azure: AI services ---
    "azure-ai-search-auth":            {"fedramp": ["IA-2", "AC-3"]},
    "azure-cognitive-cmk":             {"fedramp": ["SC-28", "SC-12"], "pci_dss": ["3.5.1"]},
    "azure-cognitive-network-rules":   {"fedramp": ["SC-7"], "pci_dss": ["1.4.1"]},
    "azure-openai-abuse-monitoring":   {"fedramp": ["SI-4"]},
    "azure-openai-content-filter":     {"fedramp": ["SI-4"]},
    "azure-openai-diagnostic-logging": {"fedramp": ["AU-2", "AU-12"]},
    "azure-openai-key-rotation":       {"fedramp": ["IA-5", "SC-12"]},
    "azure-openai-managed-identity":   {"fedramp": ["IA-2", "IA-5"]},
    "azure-openai-private-endpoint":   {"fedramp": ["SC-7"], "pci_dss": ["1.4.1"]},
    "azure-ml-compute-rbac":           {"fedramp": ["AC-3", "AC-6"]},
    "azure-ml-data-drift-monitor":     {"fedramp": ["SI-4"]},
    "azure-ml-environment-pinned":     {"fedramp": ["CM-2", "SI-7"]},
    "azure-ml-model-registration":     {"fedramp": ["CM-8"]},
    "azure-ml-workspace-encryption":   {"fedramp": ["SC-28", "SC-12"], "pci_dss": ["3.5.1"]},
    # --- Azure: Recovery Services vaults ---
    "azure-rsv-cmk":           {"fedramp": ["CP-9", "SC-28"]},
    "azure-rsv-crr":           {"fedramp": ["CP-9"]},
    "azure-rsv-exists":        {"fedramp": ["CP-9"]},
    "azure-rsv-immutability":  {"fedramp": ["CP-9", "AU-9"]},
    "azure-rsv-mua":           {"fedramp": ["CP-9", "AC-6"]},
    "azure-rsv-public-access": {"fedramp": ["SC-7"], "pci_dss": ["1.4.1"]},
    "azure-rsv-redundancy":    {"fedramp": ["CP-9"]},
    "azure-rsv-soft-delete":   {"fedramp": ["CP-9"]},
    # --- GCP: logging + audit ---
    "gcp-audit-data-access":              {"fedramp": ["AU-2", "AU-12"], "pci_dss": ["10.2.1"]},
    "gcp-dns-logging":                    {"fedramp": ["AU-2", "AU-12"], "pci_dss": ["10.2.1"]},
    "gcp-log-metric-alerts":              {"fedramp": ["AU-6", "SI-4"], "pci_dss": ["10.4.1"]},
    "gcp-log-metric-custom-role-changes": {"fedramp": ["AU-6", "SI-4"], "pci_dss": ["10.4.1"]},
    "gcp-log-metric-firewall-changes":    {"fedramp": ["AU-6", "SI-4"], "pci_dss": ["10.4.1"]},
    "gcp-log-metric-project-ownership":   {"fedramp": ["AU-6", "SI-4"], "pci_dss": ["10.4.1"]},
    "gcp-log-metric-vpc-changes":         {"fedramp": ["AU-6", "SI-4"], "pci_dss": ["10.4.1"]},
    "gcp-log-retention":                  {"fedramp": ["AU-11"], "pci_dss": ["10.5.1"]},
    "gcp-log-sink":                       {"fedramp": ["AU-2", "AU-9"]},
    # --- GCP: IAM ---
    "gcp-iam-no-allusers":       {"fedramp": ["AC-3", "AC-6"], "pci_dss": ["7.2.1"]},
    "gcp-iam-primitive-roles":   {"fedramp": ["AC-6"], "pci_dss": ["7.2.1"]},
    "gcp-iam-sa-key-rotation":   {"fedramp": ["IA-5"], "pci_dss": ["8.3.9"]},
    "gcp-iam-sa-not-admin":      {"fedramp": ["AC-6"], "pci_dss": ["7.2.1"]},
    "gcp-iam-sa-token-creator":  {"fedramp": ["AC-6"]},
    "gcp-iam-workload-identity": {"fedramp": ["IA-5", "IA-2"], "pci_dss": ["8.6.1"]},
    # --- GCP: compute + GKE ---
    "gcp-compute-default-sa-full-scope": {"fedramp": ["AC-6"]},
    "gcp-compute-no-external-ip":        {"fedramp": ["SC-7"], "pci_dss": ["1.4.1"]},
    "gcp-compute-os-login":              {"fedramp": ["AC-3", "IA-2"]},
    "gcp-compute-serial-port":           {"fedramp": ["CM-7"]},
    "gcp-compute-shielded-vm":           {"fedramp": ["SI-7"]},
    "gcp-gke-network-policy":            {"fedramp": ["SC-7", "AC-4"], "pci_dss": ["1.3.1"]},
    "gcp-gke-node-auto-upgrade":         {"fedramp": ["SI-2"], "pci_dss": ["6.3.3"]},
    "gcp-gke-private-cluster":           {"fedramp": ["SC-7"], "pci_dss": ["1.4.1"]},
    "gcp-gke-workload-identity":         {"fedramp": ["IA-2", "IA-5"], "pci_dss": ["8.6.1"]},
    # --- GCP: Cloud Run ---
    "gcp-cloudrun-binary-authorization":   {"fedramp": ["SI-7", "CM-5"]},
    "gcp-cloudrun-ingress-restricted":     {"fedramp": ["SC-7"], "pci_dss": ["1.4.1"]},
    "gcp-cloudrun-no-default-sa":          {"fedramp": ["AC-6", "IA-2"]},
    "gcp-cloudrun-no-plaintext-secrets":   {"fedramp": ["IA-5", "SC-28"], "pci_dss": ["8.6.2"]},
    "gcp-cloudrun-no-unauth-access":       {"fedramp": ["AC-3", "IA-2"], "pci_dss": ["7.2.1"]},
    # --- GCP: networking ---
    "gcp-firewall-admin-ports":         {"fedramp": ["SC-7", "AC-4"], "pci_dss": ["1.3.1"]},
    "gcp-network-default-not-created":  {"fedramp": ["SC-7", "CM-7"]},
    "gcp-subnet-flow-logs":             {"fedramp": ["AU-2", "SI-4"], "pci_dss": ["10.2.1"]},
    "gcp-subnet-private-google-access": {"fedramp": ["SC-7"]},
    # --- GCP: KMS ---
    "gcp-kms-key-rotation": {"fedramp": ["SC-12"], "pci_dss": ["3.7.4"]},
    # --- GCP: storage + BigQuery ---
    "gcp-bigquery-cmek":              {"fedramp": ["SC-28", "SC-12"], "pci_dss": ["3.5.1"]},
    "gcp-bigquery-public-access":     {"fedramp": ["SC-7", "AC-3"], "pci_dss": ["1.4.1"]},
    "gcp-storage-access-logging":     {"fedramp": ["AU-2", "AU-12"], "pci_dss": ["10.2.1"]},
    "gcp-storage-bucket-public-access": {"fedramp": ["SC-7", "AC-3"], "pci_dss": ["1.4.1"]},
    "gcp-storage-retention-policy":   {"fedramp": ["SI-12"]},
    "gcp-storage-uniform-access":     {"fedramp": ["AC-3"]},
    "gcp-storage-versioning":         {"fedramp": ["CP-9"]},
    # --- GCP: Cloud SQL ---
    "gcp-sql-backups":     {"fedramp": ["CP-9"]},
    "gcp-sql-no-public-ip": {"fedramp": ["SC-7"], "pci_dss": ["1.4.1"]},
    "gcp-sql-require-ssl":  {"fedramp": ["SC-8", "SC-13"], "pci_dss": ["4.2.1"]},
    # --- GitHub ---
    "github-branch-protection": {"fedramp": ["CM-3", "CM-5"]},
    "github-enforce-admins":    {"fedramp": ["CM-5", "AC-6"]},
    "github-no-force-push":     {"fedramp": ["CM-5", "SI-7"]},
    "github-pr-reviews":        {"fedramp": ["CM-3", "SA-11"]},
    "github-repo-access":       {"fedramp": ["AC-3", "AC-6"], "pci_dss": ["7.2.1"]},
    "github-status-checks":     {"fedramp": ["CM-3", "SA-11"]},
}
