name: CISOCopilot
options:
  bundleIdPrefix: ai.transilience
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

packages:
  WebRTC:
    url: https://github.com/stasel/WebRTC
    from: 130.0.0

settings:
  base:
    DEVELOPMENT_TEAM: 2G875YX5NV
    SWIFT_VERSION: "5.10"
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    CODE_SIGN_STYLE: Automatic
    GENERATE_INFOPLIST_FILE: NO
    INFOPLIST_FILE: CISOCopilot/Info.plist

targets:
  CISOCopilot:
    type: application
    platform: iOS
    configFiles:
      Debug:   Local.xcconfig
      Release: Local.xcconfig
    sources:
      - path: CISOCopilot
    dependencies:
      - package: WebRTC
        product: WebRTC
    entitlements:
      path: CISOCopilot/CISOCopilot.entitlements
      properties:
        aps-environment: development
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.transilience.cisocopilot
        TARGETED_DEVICE_FAMILY: "1"
